#!/bin/bash
find . -name "*.h" -o -name "*.c" -o -name "*.cc" -o -name "*.csp" > cscope.files
cscope -bkq -i cscope.files
ctags -R --c-kinds=+p --fields=+iaS  --extra=+q #/usr/include/
#ctags -R --c++-kinds=+p --fields=+iaS --extra=+q /usr/include/c++/4.4.3/
#cscope add ./cscope.out
